---
name: Clang-format
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        if: ${{ github.ref != 'refs/heads/main' }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Actions checkout
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run clang format lint
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: DoozyX/clang-format-lint-action@v0.15
        with:
          source: "src"
          exclude: "src/protobuf"
          extensions: "cpp,hpp,h"
          clangFormatVersion: 15
          inplace: true

      - name: Run add and commit
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: github-actions[bot]@users.noreply.github.com
          message: "Code format - (Clang-format)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
